apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webapp.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set_real_ip_from    {{ .Values.webapp.ingress.setRealIPfrom }};
      real_ip_header      X-Forwarded-For;
      add_header Cache-Control no-store always;
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.webapp.hostname}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "webapp.fullname" . }}
                port:
                  number: {{ .Values.webapp.service.port }}

  tls:
    - hosts:
        - {{ .Values.webapp.hostname | quote }}
      secretName: {{ .Values.webapp.ingress.secretName }}
