const HOME_PATH = '/home';
const OPEN_ACCOUNT_MAIN_PATH = '/open-account/main';

export interface IRouteConfig {
  path: string;
  title?: string;
  defaultBackTo?: string;
  noBottomNav?: boolean;
  noRightButtons?: boolean;
  noLeftNav?: boolean;
  isTitleVisible?: boolean;
  isBackButtonVisible?: boolean;
  isProfileButtonVisible?: boolean;
  isLangSwitcherVisible?: boolean;
  isRoundedDesktopHeader?: boolean;
  isRoundedDesktopLeftNav?: boolean;
}

export const ROUTES = {
  root: { path: '/', title: 'Root' },
  auth: { path: '/auth', title: 'Mobile Authentication' },
  app: { path: '/app', title: 'Redirect to Mobile App' },
  login: { path: '/login', title: 'Login' },
  verifyDeviceWarning: { path: '/verify-device-warning', title: 'Verify Device Warning' },
  verifyDevice: { path: '/verify-device', title: 'Verify Device' },
  started: { path: '/started', title: 'Start Page' },
  registration: { path: '/register', title: 'Registration' },
  registrationCode: { path: '/register/code', title: 'SMS code' },
  setupBiometric: { path: '/setup-biometric', title: 'Setup Biometric' },
  forgotPassword: { path: '/forgot-password', title: 'Forgot password' },
  forgotPasswordCode: { path: '/forgot-password/sms-code', title: 'SMS code' },
  forgotUsernameSent: { path: '/username-sent', title: 'Forgot username' },
  checkCode: { path: '/check-code', title: 'Check code' },
  changePassword: { path: '/change-password', title: 'Change Password' },
  onboarding: { path: '/onboarding', title: 'Onboarding: Welcome' },
  onboardingHome: { path: '/onboarding/home', title: 'Onboarding: Home' },
  onboardingFirstSteps: { path: '/onboarding/first-steps', title: 'Onboarding: First steps' },
  onboardingLanguageSelection: { path: '/onboarding/language-selection', title: 'Onboarding: Language Selection' },
  home: { path: HOME_PATH, title: 'Home' },
  logout: { path: '/logout', title: 'Logout' },
  invite: { path: '/invite', title: 'Invite' },
  wellness: { path: '/wellness', title: 'Financial Wellness', isLangSwitcherVisible: false },
  wellnessQuestion: { path: '/wellness/:questionName?', title: 'Wellness Question' },
  balancesTransactions: { path: '/balances-transactions', title: 'Balances & Transactions', noBottomNav: true, noRightButtons: true },
  profile: { path: '/profile', title: 'Profile', noBottomNav: true, isTitleVisible: false },
  profileChangePassword: { path: '/profile/change-password', title: 'Profile Change Password' },
  searchPayee: { path: '/search-payee', title: 'Search Payee' },
  spendingTransactions: { path: '/checking-account/transactions', title: 'Transactions' },
  savingBudgetTransactions: { path: '/saving-budget/transactions', title: 'Transactions' },
  success: { path: '/success', title: 'Success' },
  myIdSuccess: {
    path: '/open-cash-account/success',
    title: 'Cash Account Opening',
    noBottomNav: true,
    noRightButtons: true,
  },
  myIdPending: {
    path: '/open-cash-account/pending',
    title: 'Cash Account Opening',
    noBottomNav: true,
    noRightButtons: true,
  },
  myIdMatch: {
    path: '/open-cash-account/match',
    title: 'Cash Account Opening',
    noBottomNav: true,
    noRightButtons: true,
  },

  welcome: { path: '/welcome', title: 'Welcome' },
  attune: {
    path: '/attune',
    title: 'MyMoney Journey',
    noBottomNav: true,
  },
  playPercUp: { path: '/playpercup', title: 'Play Tenx Plays' },
  enroll: {
    path: '/tenx-pay/enroll',
    title: 'Move Money',
    noBottomNav: true,
    isTitleVisible: false,
    noLeftNav: true,
    isRoundedDesktopHeader: true,
  },
  termsAndConditions: {
    path: '/tenx-pay/terms-and-conditions',
    title: 'Tenx Pay',
    isTitleVisible: false,
    noBottomNav: true,
    defaultBackTo: HOME_PATH,
    isRoundedDesktopHeader: true,
    isRoundedDesktopLeftNav: true,
  },
  accountApproved: {
    path: '/tenx-pay/account-approved',
    title: 'Tenx Pay',
    noBottomNav: true,
    isTitleVisible: false,
  },
  emailVerification: {
    path: '/tenx-pay/email-verification',
    title: 'Tenx Pay',
    noBottomNav: true,
    isTitleVisible: false,
    noRightButtons: true,
    isRoundedDesktopHeader: true,
    isRoundedDesktopLeftNav: true,
  },
  verificationCode: {
    path: '/tenx-pay/verification-code',
    title: 'Verification Code',
    isTitleVisible: false,
    noBottomNav: true,
  },
  tenxPayHome: {
    path: '/tenx-pay/home',
    title: 'Tenx Pay',
    noBottomNav: true,
    defaultBackTo: HOME_PATH,
    isTitleVisible: false,
  },
  starter: { path: '/open-account/starter', title: 'Cash Account Starter', isTitleVisible: false },
  prep: { path: '/open-account/prep', title: 'Prep', defaultBackTo: HOME_PATH },
  openAccountMain: {
    path: OPEN_ACCOUNT_MAIN_PATH,
    title: 'Cash Account Opening',
    noBottomNav: true,
    noRightButtons: true,
  },
  myAccountAccounts: {
    path: '/open-account/my-account/accounts',
    title: 'Cash Account Opening',
    noBottomNav: true,
    noRightButtons: true,
  },
  myAccountDisclosures: {
    path: '/open-account/my-account/disclosures',
    title: 'Cash Account Opening',
    noBottomNav: true,
    noRightButtons: true,
  },
  myAccountJointAccounts: {
    path: '/open-account/my-account/joint-accounts',
    title: 'Cash Account Opening',
    defaultBackTo: '/open-account/my-info/tax-id',
    noBottomNav: true,
    noRightButtons: true,
  },
  myId: {
    path: '/open-cash-account/my-id',
    title: 'Cash Account Opening',
    noBottomNav: true,
    noRightButtons: true,
  },
  truliooUpload: {
    path: '/open-cash-account/upload',
    title: 'Cash Account Opening',
  },
  myInfoEConsent: {
    path: '/open-account/my-info/e-consent',
    title: 'Cash Account Opening',
    defaultBackTo: OPEN_ACCOUNT_MAIN_PATH,
    noBottomNav: true,
    noRightButtons: true,
  },
  myInfoDisclosures: {
    path: '/open-account/my-info/disclosures',
    title: 'Cash Account Opening',
    defaultBackTo: '/open-account/prep',
    noBottomNav: true,
    noRightButtons: true,
  },
  myInfoName: {
    path: '/open-account/my-info/name',
    title: 'Cash Account Opening',
    defaultBackTo: '/open-account/my-info/disclosures',
    noBottomNav: true,
    noRightButtons: true,
  },
  myInfoAge: {
    path: '/open-account/my-info/age',
    title: 'Cash Account Opening',
    defaultBackTo: '/open-account/my-info/email',
    noBottomNav: true,
    noRightButtons: true,
  },
  myInfoHomeAddress: {
    path: '/open-account/my-info/address',
    title: 'Cash Account Opening',
    defaultBackTo: '/open-account/my-info/name',
    noBottomNav: true,
    noRightButtons: true,
  },
  myInfoTaxId: {
    path: '/open-account/my-info/tax-id',
    title: 'Cash Account Opening',
    defaultBackTo: '/open-account/my-info/age',
    noBottomNav: true,
    noRightButtons: true,
  },
  myInfoEmailUsername: {
    path: '/open-account/my-info/email',
    title: 'Cash Account Opening',
    defaultBackTo: '/open-account/my-info/address',
    noBottomNav: true,
    noRightButtons: true,
  },
  myInfoVerifySms: {
    path: '/open-account/my-info/verify-sms',
    title: 'Cash Account Opening',
    noBottomNav: true,
    noRightButtons: true,
  },
  myInfoAdditionalDetails: {
    path: '/open-account/my-info/additional-details',
    title: 'Cash Account Opening',
    defaultBackTo: '/open-account/my-info/tax-id',
    noBottomNav: true,
    noRightButtons: true,
  },
  myInfoSummary: {
    path: '/open-account/my-info/summary',
    title: 'Cash Account Opening',
    defaultBackTo: '/open-account/my-info/additional-details',
    noBottomNav: true,
    noRightButtons: true,
  },
  myInfoVeriticationResult: {
    path: '/open-account/my-info/result',
    title: 'Cash Account Opening',
    defaultBackTo: '/open-account/my-info/summary',
    noBottomNav: true,
    noRightButtons: true,
  },
  transactionsHistory: { path: '/transactions/history', title: 'Transactions History' },
  mainMenu: {
    path: '/menu',
    title: 'Menu',
  },
  subscriptions: { path: '/subscriptions', title: 'Susbscriptions', isTitleVisible: false, noBottomNav: true },
  tenxPayBalance: { path: '/tenx-pay/home', title: 'Tenx Pay: Balance' },
  internalTransfer: {
    path: '/accounts/internal-transfer',
    title: 'Home',
    noBottomNav: true,
    noRightButtons: true,
    defaultBackTo: '/home',
  },
  notificationSettings: { path: '/notification-settings', title: 'Notification Settings', isTitleVisible: false, noBottomNav: true },
  helpAndSupport: {
    path: '/help-and-support/:groupId?/:questionName?',
    title: 'Menu',
    defaultBackTo: '/menu',
    noBottomNav: true,
    isTitleVisible: false,
  },
  helpAndSupportSearch: {
    path: '/help-and-support/search/:questionName?',
    title: '',
    defaultBackTo: '/help-and-support',
    noBottomNav: true,
  },
  tenxPayHistory: {
    path: '/tenx-pay/history',
    title: '',
    noBottomNav: true,
    isTitleVisible: false,
  },
  productsInterests: { path: '/products-interests', title: 'Get updated when we launch our products.' },
  successfulAccountOpen: { path: '/account-open/success', title: 'Account Open Success' },
  depositOnboard: { path: '/deposit-onboard', title: '', noBottomNav: true, noRightButtons: true, isTitleVisible: false },
  startDeposit: { path: '/start-deposit', title: '3 Great Features', noBottomNav: true, noRightButtons: true },
  directDeposit: { path: '/direct-deposit', title: '3 Great Features', noBottomNav: true, noRightButtons: true },
  setUpDeposit: { path: '/set-up-deposit', title: '', noBottomNav: true, noRightButtons: true },
  disclosures: { path: '/disclosures', title: 'Disclosures', defaultBackTo: '/menu', isTitleVisible: true },
  moveMoney: {
    path: '/move-money',
    title: 'Move Money',
    isProfileButtonVisible: false,
  },
  moveMoneyOnboarding: {
    path: '/money-onboarding',
    title: 'Move Money',
  },
  addMoney: {
    path: '/add-money',
    title: 'From my outside account',
    noRightButtons: true,
    noBottomNav: true,
    defaultBackTo: '/move-money',
  },
  addFunds: {
    path: '/add-funds',
    title: '',
    noRightButtons: true,
    noBottomNav: true,
  },
  sendMoneyPage: {
    path: '/send-money-page',
    title: '',
    noRightButtons: true,
    noBottomNav: true,
    defaultBackTo: '/move-money',
  },
  sendFunds: {
    path: '/send-funds',
    title: '',
    noRightButtons: true,
  },
  addNewSourceDebit: {
    path: '/add-new-source',
    title: 'From my outside account',
    noRightButtons: true,
    noBottomNav: true,
    defaultBackTo: '/add-money',
  },
  addNewBankAccount: {
    path: '/add-new-bank-account',
    title: 'From my outside account',
    noRightButtons: true,
    noBottomNav: true,
    defaultBackTo: '/add-money',
  },
  truliooTransaction: {
    path: '/trulioo-transaction',
    title: 'Trulioo transaction',
  },
  addNeedsGoalsAccount: {
    path: '/add-account',
    title: 'Home',
    isLangSwitcherVisible: false,
  },
  acceptInvite: {
    path: '/accept-invite/:inviteId',
    title: '',
  },
  successAddNeedsGoalsAccount: {
    path: '/add-account/success',
    title: 'Home',
  },
  securityPrivacy: {
    path: '/security_privacy',
    title: '',
    defaultBackTo: '/menu',
    noBottomNav: true,
  },
  accountInformation: {
    path: '/account_information',
    title: 'Menu',
    noBottomNav: true,
    isTitleVisible: false,
    defaultBackTo: '/menu',
  },
  selectedAccountInformation: {
    path: '/account_information/selected',
    title: 'Menu',
    noBottomNav: true,
    isTitleVisible: false,
  },
  statementsAndDocuments: {
    path: '/statements',
    title: 'Menu',
    defaultBackTo: '/menu',
    isTitleVisible: false,
    noBottomNav: true,
  },
  statementsIframe: {
    path: '/statements-iframe',
    title: 'Menu',
    defaultBackTo: '/menu',
    isTitleVisible: false,
    noBottomNav: true,
  },
  pennyJar: {
    path: '/penny-jar',
    title: '',
    isTitleVisible: false,
    noBottomNav: true,
    noLeftNav: true,
  },
  pennyJarSetup: {
    path: '/penny-jar/setup',
    title: '',
    isTitleVisible: false,
    noBottomNav: true,
    noLeftNav: true,
  },
  pennyJarActivate: {
    path: '/penny-jar/activate',
    title: '',
    isTitleVisible: false,
    noBottomNav: true,
    noLeftNav: true,
  },
  enableThreeGreatFeatures: {
    path: '/enable-three-great-features',
    title: 'Enable 3 great features',
    isTitleVisible: false,
    noBottomNav: true,
    noRightButtons: true,
    isLangSwitcherVisible: false,
  },
  uploadDocument: {
    path: '/open-account/upload-document',
    title: 'Cash Account Opening',
    noBottomNav: true,
    noRightButtons: true,
  },
  atmLocations: {
    path: '/atm-locations',
    title: 'ATM Locations',
    defaultBackTo: '/move-money',
    noBottomNav: true,
    isTitleVisible: false,
  },
  FAQRoute: {
    path: ':category?/:answer?',
    title: 'Using Another App Or Provider',
    defaultBackTo: '/move-money',
  },
  notificationsCenter: {
    path: '/notifications-center',
    title: '',
    defaultBackTo: HOME_PATH,
    noBottomNav: true,
  },
  notificationsCenterItem: {
    path: '/notifications-center/:id',
    title: 'Notifications Center',
    defaultBackTo: '/notifications-center',
    noBottomNav: true,
  },
  forgotDataUsernameSent: {
    path: '/username-sent',
    title: 'Username has been sent',
  },
  forgotDataInformationSent: {
    path: '/information-sent',
    title: 'Information has been sent',
  },
};
