import { IAdditionalInformationHandlerConfig } from './AdditionalInformationHandler.types';

export const MODAL_DATA: IAdditionalInformationHandlerConfig = {
  goalsAndTools: {
    TITLE: 'inviteEarn.AdditionalInformation',
    TITLE_COLOR: 'blue',
    TEXT: 'learnPlay.All customers who earn 5000 Tenx Points by September 30, 2023, are eligible to earn a $10 account opening bonus upon opening a Tenx Cash Account.',
    TEXT_COLOR: 'charcoal70',
    FONT_WEIGHT: 'R',
  },
  invite: {
    TITLE: 'inviteEarn.AdditionalInformation',
    TITLE_COLOR: 'charcoal',
    TEXT: `inviteEarn.YourReferralReceiveTextOrEmailFromTenx`,
    TEXT_COLOR: 'charcoal70',
    FONT_WEIGHT: 'R',
    TOP_POSITION: '25%',
  },
  universalInfo: {
    TITLE: 'directDeposit.Direct Deposit',
    TITLE_COLOR: 'charcoal',
    TEXT: 'directDeposit.Setting up direct deposit ...',
    TEXT_COLOR: 'charcoal70',
    FONT_WEIGHT: 'R',
    TOP_POSITION: '25%',
  },
  externalTransferInfo: {
    TITLE: '',
    TITLE_COLOR: 'charcoal',
    TEXT: 'externalTransfer.TransfersInfo',
    TEXT_COLOR: 'charcoal70',
    FONT_WEIGHT: 'R',
    TOP_POSITION: '25%',
  },
  preferredName: {
    TITLE: "profile.What is 'Preferred Name'?",
    TITLE_COLOR: 'charcoal',
    TEXT: 'profile.Your Preferred Name is the name we will use when we  call, write or chat with you.',
    TEXT_COLOR: 'charcoal70',
    FONT_WEIGHT: 'R',
  },
  myInfoAgeValidation: {
    TITLE: 'myInfo.Reminder',
    TITLE_COLOR: 'charcoal',
    TEXT: 'myInfo.You need to be at least 18 or older to...',
    TEXT_COLOR: 'charcoal70',
    FONT_WEIGHT: 'R',
    TOP_POSITION: '25%',
    BUTTON_TEXT: 'myInfo.Continue',
    PRESET: 'primary',
    BUTTON_MARGIN_TOP: '20px',
  },
  routingNumber: {
    TITLE: 'accountInformation.Routing Number',
    TITLE_COLOR: 'charcoal',
    TEXT: 'accountInformation.Your Routing Number is',
    TEXT_COLOR: 'charcoal70',
    FONT_WEIGHT: 'R',
  },
  accountNumber: {
    TITLE: 'accountInformation.Account Number',
    TITLE_COLOR: 'charcoal',
    TEXT: 'accountInformation.Your Account Number is',
    TEXT_COLOR: 'charcoal70',
    FONT_WEIGHT: 'R',
  },
  externalAvailable: {
    TITLE: 'externalTransfer.WhenWillAvailable',
    TITLE_COLOR: 'charcoal',
    TEXT: 'externalTransfer.AvailableModalText1',
    SECOND_TEXT: 'externalTransfer.AvailableModalText2',
    THIRD_TEXT: 'externalTransfer.AvailableModalText3',
    TEXT_COLOR: 'charcoal70',
    FONT_WEIGHT: 'R',
  },
};
